#theme: jekyll-theme-minimal
remote_theme: pmarsceill/just-the-docs
search_enabled: true

color_scheme: sekha-dark.scss

title: Sekha
tagline: "Pāḷi"
description: "Notes of a seeker"
type: website

# enable theme for local usage
#theme: "just-the-docs"
